# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
group=de.thedead2.customadvancements
java_version=21

# Mod
mod_name=Custom Advancements
mod_id=customadvancements
version=8.0.0
mod_description=
mod_license=GPL-3.0
mod_authors=The_Dead_2
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/custom-advancements
mod_github = https://github.com/thedead2/customadvancements


# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.22)

# Mixin
mixin_version=0.7-SNAPSHOT
mixin_extras_version = 0.4.1


# Parchment Mappings, see https://parchmentmc.org/docs/getting-started.html for new versions
parchment_mc_version=1.21.1
parchment_version=2024.11.17

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.116.10+1.21.1
fabric_short_version=0.116.10
fabric_loader_version=0.18.6
fabric_loom_version=1.9-SNAPSHOT

# NeoForge, see https://neoforged.net for new versions
neoforge_version=21.1.47
neoforge_loader_version_range=[4,)
neogradle_version=7.0.178

# Dependencies
forgeconfig_api_port_version=21.1.6



# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.configureondemand=true
