plugins {
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${mod_id}-neoforge-${minecraft_version}"
}

apply from: rootProject.file('gradle/genAccessTransformers.gradle')

neoForge {
    version = "${neoforge_version}"

    parchment {
        minecraftVersion = "${parchment_mc_version}"
        mappingsVersion = "${parchment_version}"
    }

    // Automatically enable neoforge AccessTransformers if the file exists
    if (project.ext.awFile.exists()) {
        accessTransformers {
            file(project.ext.atFile)
        }
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'terminal.ansi', 'true'

            logLevel = org.slf4j.event.Level.DEBUG

            gameDirectory = project.file("run/client")
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'terminal.ansi', 'true'

            logLevel = org.slf4j.event.Level.DEBUG

            gameDirectory = project.file("run/server")
        }
        data {
            data()

            systemProperty 'terminal.ansi', 'true'
            logLevel = org.slf4j.event.Level.DEBUG

            def commonGeneratedDir = rootProject.file('common/src/generated/resources')

            programArguments.addAll '--mod', "${mod_id}",
                    '--output', commonGeneratedDir.getAbsolutePath(),
                    '--all'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
            sourceSet project(":mc_libs").sourceSets.main
        }
    }
}

// Exclude Fabric Loader from NeoForge
configurations {
    compileClasspath { exclude group: 'net.fabricmc', module: 'fabric-loader' }
    runtimeClasspath { exclude group: 'net.fabricmc', module: 'fabric-loader' }
}

tasks.named('processResources') {
    dependsOn tasks.named('generateAccessTransformers')
    exclude 'customadvancements.refmap.json'
}

tasks.named('createMinecraftArtifacts') {
    dependsOn tasks.named('generateAccessTransformers')
}


tasks.named('sourcesJar') {
    dependsOn tasks.named('generateAccessTransformers')
    exclude 'customadvancements.accesswidener'
}

tasks.named('jar', Jar) {
    exclude 'customadvancements.accesswidener'
}
