plugins {
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${mod_id}"
}

// Automatically enable neoforge AccessTransformers if the file exists
if (file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
    minecraft.accessTransformers.file file('src/main/resources/META-INF/accesstransformer.cfg')
}

neoForge {
    version = "${neoforge_version}"

    parchment {
        minecraftVersion = "${parchment_mc_version}"
        mappingsVersion = "${parchment_version}"
    }


    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            gameDirectory = project.file("run/client")
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            gameDirectory = project.file("run/server")
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

dependencies {
    compileOnly project(":common")
}

// Exclude Fabric Loader from NeoForge
configurations {
    compileClasspath { exclude group: 'net.fabricmc', module: 'fabric-loader' }
    runtimeClasspath { exclude group: 'net.fabricmc', module: 'fabric-loader' }
}